import { EnvironmentRequirement } from './../../generated/prisma/index.d';
import express from "express";
const router = express.Router();
import AuthRoute from "./auth/AuthRoutes";
import ProjectRoute from "./project/ProjectRoutes";
import ReleaseRoute from "./release/ReleaseRoute";
import ChangeLogItemRoute from "./changeLogItem/ChangeLogItemRoutes";
import EnvironmentRequirementRoute from "./environmentRequirement/EnvironmentRequirementRoute";
import KnowledgeDocRoute from "./knowledgeDoc/KnowledgeDocRoutes";
import TagRoute from "./tag/TagRoutes";
import EcoSystemRoute from "./ecosystemRelease/EcosystemReleaseRoutes";

router.use("/auth",AuthRoute);
router.use("/projects",ProjectRoute);
router.use("/releases",ReleaseRoute);
router.use("/changeLogItems",ChangeLogItemRoute);
router.use("/environmentRequirements",EnvironmentRequirementRoute);
router.use("/knowledgeDocs",KnowledgeDocRoute);
router.use("/tags",TagRoute);
router.use("/ecosystemReleases",EcoSystemRoute);
export default router;
