export enum ErrorCode {
 
  UNAUTHORIZED = "UNAUTHORIZED",                 // No token / invalid token
  FORBIDDEN = "FORBIDDEN",                       // Not allowed
  SESSION_EXPIRED = "SESSION_EXPIRED",

 
  BAD_REQUEST = "BAD_REQUEST",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  MISSING_FIELDS = "MISSING_FIELDS",

 
  NOT_FOUND = "NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
 
  CONFLICT = "CONFLICT",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  DUPLICATE_ENTRY = "DUPLICATE_ENTRY",
 
  PRISMA_CLIENT_ERROR = "PRISMA_CLIENT_ERROR",
  PRISMA_NOT_FOUND = "PRISMA_NOT_FOUND",
  PRISMA_VALIDATION_ERROR = "PRISMA_VALIDATION_ERROR",
  PRISMA_CONSTRAINT_FAILED = "PRISMA_CONSTRAINT_FAILED",
  PRISMA_P2002 = "PRISMA_P2002",   // Unique constraint failed
  PRISMA_P2003 = "PRISMA_P2003",   // Foreign key constraint
  PRISMA_P2025 = "PRISMA_P2025",   // Record not found
 
  DATABASE_ERROR = "DATABASE_ERROR",
  CONNECTION_ERROR = "CONNECTION_ERROR",
  TRANSACTION_FAILED = "TRANSACTION_FAILED",

 
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  TIMEOUT = "TIMEOUT",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  
 
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
}
